### ISSUE TITLE
Display Pigeon Heading with Compass Widget

### ISSUE THREAD

**Issue by AhmedFaisal101** [Team2338/2022_BAB_B#3]

**Comment by geet-gambhir** [comment]
done in https://github.com/Team2338/2022_BAB_B/commit/14ca0d9ab0bdc2c13252409f178f96dcc506e49e

**Comment by geet-gambhir** [comment]
edit: done from _this_ https://github.com/Team2338/2022_BAB_B/pull/9/commits/2820080796d7b501dd4462c8680b4c19ce8ee016
